export let products = [
    // {
    //     // id: "1",
    //     title: "Caja De Hallowen",
    //     price: 20000,
    //     stock: 10,
    //     imageUrl: "https://res.cloudinary.com/ddd3z2fug/image/upload/v1730219566/1CCAECA8-96BF-401C-AB4A-E0A1486FCC76_qx0me9.png",
    //     description: "caja de 25x25x25 de tematica hallowen",
    //     brand: "LaCaja",
    //     category: "De Temporada",
    // },
    // {
    //     // id: "2",
    //     title: "Caja Misteriosa Grande",
    //     price: 15000,
    //     stock: 10,
    //     imageUrl: "https://res.cloudinary.com/ddd3z2fug/image/upload/v1730222269/mystery_box__41855_ejfbi7.jpg",
    //     description: "caja de 30x30x30 con objetos misteriosos",
    //     brand: "LaCaja",
    //     category: "Mistery Box",
    // },
    {
        // id: "3",
        title: "Caja Misteriosa Mediana",
        price: 12000,
        stock: 10,
        imageUrl: "https://res.cloudinary.com/ddd3z2fug/image/upload/v1730222269/mystery_box__41855_ejfbi7.jpg",
        description: "caja de 25x25x25 con objetos misteriosos",
        brand: "LaCaja",
        category: "Mistery Box",
    },
    {
        // id: "4",
        title: "Caja Misteriosa Pequeña",
        price: 10000,
        stock: 10,
        imageUrl: "https://res.cloudinary.com/ddd3z2fug/image/upload/v1730222269/mystery_box__41855_ejfbi7.jpg",
        description: "caja de 20x20x25 con objetos misteriosos",
        brand: "LaCaja",
        category: "Mistery Box",
    },
    {
        // id: "5",
        title: "Caja Personalizada",
        price: 20000,
        stock: 10,
        imageUrl: "https://res.cloudinary.com/ddd3z2fug/image/upload/v1730222269/mystery_box__41855_ejfbi7.jpg",
        description: "caja de 30x30x30 con objetos de la tematica que tu eligas",
        brand: "LaCaja",
        category: "personalizada",
    },
]